name: dash-cyto
channels:
  - defaults
dependencies:
  - python=3.7.6
  - numpy=1.19.2
  - pandas=1.2.1
  - networkx=2.5
  - plotly=4.14.3
  - scikit-learn=0.23.2
  - pip=20.1.1
  - matplotlib=3.3.2
  - spyder=4.1.5
  - pip:
    - dash-renderer==1.2.2
    - dash==1.7.0
    - dash-core-components==1.6.0
    - dash-html-components==1.0.2
    - dash-cytoscape==0.2.0
    - dash-bootstrap-components==0.8.1
    - dash-table==4.5.1
